force-app/main/default/objects/Rental_Contract__c/Rental_Contract__c.object-meta.xml
<CustomObject>
    <description>Car rental contract formed by a rental company and one of its customers.</description>
    <label>Rental Contract</label>
    <nameField>
        <displayFormat>RC-{YY}{0000}</displayFormat>
        <label>Rental Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Contract__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>The company that is offering a contract.</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>The customer who is signing the contract.</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Return_Date__c</fullName>
    <description>The date when the customer is expected to return the vehicle.</description>
    <label>Expected Return Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The date when the rental contract is formed.</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the contract.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Base_Rental_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rental_Rate__c</fullName>
    <label>Base Rental Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand New</fullName>
                <default>true</default>
                <label>Brand New</label>
            </value>
            <value>
                <fullName>Like New</fullName>
            </value>
            <value>
                <fullName>Great</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Okay</fullName>
            </value>
            <value>
                <fullName>Worn</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checked In</fullName>
                <default>true</default>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Lost/Stolen</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Identification_Number__c</fullName>
    <description>The unique number assigned to this vehicle.</description>
    <externalId>true</externalId>
    <label>Vehicle Identification Number</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <label>Vehicle Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Car_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa-Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston-Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Bugatti</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citroen</fullName>
    </customValue>
    <customValue>
        <fullName>Daewoo</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Geely</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Koenigsegg</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Lancia</fullName>
    </customValue>
    <customValue>
        <fullName>Tesla</fullName>
    </customValue>
    <description>List of available automobile brands.
Popular brands fetched from:
- https://www.carlogos.org/popular-car-brands/
- https://www.topspeed.com/cars/makes/</description>
    <masterLabel>Car Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TopThreeListControllerTest.cls
// This this has 75% code coverage.
@isTest
private class TopThreeListControllerTest {
    
    @isTest static void Test1() {
        // ------------- Test Data Setup ------------- //
        //
        // Create 4 vehicles. ---------------- 
        vehicle__c v1 = new vehicle__c(Name= 'v1', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V001', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model 3', 
                                           Vehicle_Year__c = 2018);
        insert v1;
        vehicle__c v2 = new vehicle__c(Name= 'v2', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V002', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model S', 
                                           Vehicle_Year__c = 2018);
        insert v2;
        vehicle__c v3 = new vehicle__c(Name= 'v3', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V003', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model Y', 
                                           Vehicle_Year__c = 2018);
        insert v3;
        vehicle__c v4 = new vehicle__c(Name= 'v3', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V004', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model Y', 
                                           Vehicle_Year__c = 2018);
        insert v4;
        vehicle__c v5 = new vehicle__c(Name= 'v3', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V005', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model Y', 
                                           Vehicle_Year__c = 2018);
        insert v5;
        vehicle__c v6 = new vehicle__c(Name= 'v2', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V006', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model S', 
                                           Vehicle_Year__c = 2018);
        insert v6;
        vehicle__c v7 = new vehicle__c(Name= 'v2', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V007', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model S', 
                                           Vehicle_Year__c = 2018);
        insert v7;
        vehicle__c v8 = new vehicle__c(Name= 'v8', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V008', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model S', 
                                           Vehicle_Year__c = 2018);
        insert v8;
        vehicle__c v9 = new vehicle__c(Name= 'v9', 
                                           Base_Rental_Rate__c = 50, 
                                           Condition__c = 'Like New', 
                                           Vehicle_Identification_Number__c = 'V009', 
                                           Vehicle_Make__c = 'Tesla', 
                                           Vehicle_Model__c = 'Model S', 
                                           Vehicle_Year__c = 2018);
        insert v9;
        //  ---------------- Create 4 vehicles.
        // 
        // Create 4 rental contracts 1 contact and 1 account. ---------------- 
        Contact c1 = new Contact(LastName = 'C1');
        insert c1;
        Account a1 = new Account(Name = 'A1');
        insert a1;
        Rental_Contract__c rc1 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v1.Id);
        insert rc1;
        Rental_Contract__c rc2 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v2.Id);
        insert rc2;
        Rental_Contract__c rc3 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v3.Id);
        insert rc3;
        Rental_Contract__c rc4 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v4.Id);
        insert rc4;
        Rental_Contract__c rc5 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v5.Id);
        insert rc5;
        Rental_Contract__c rc6 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v6.Id);
        insert rc6;
        Rental_Contract__c rc7 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v7.Id);
        insert rc7;
        Rental_Contract__c rc8 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v8.Id);
        insert rc8;
        Rental_Contract__c rc9 = new Rental_Contract__c(Company__c = a1.Id, 
                                                        Customer__c = c1.Id, 
                                                        Expected_Return_Date__c = Date.parse('10/15/2021'), 
                                                        Issue_Date__c = Date.today(), 
                                                        Status__c = 'Active', 
                                                        Vehicle__c = v9.Id);
        insert rc9; 
        // ---------------- Create 4 rental contracts 1 contact and 1 account.
        

        // ------------- Perform Test ------------- //
        Test.startTest();
        List<vehicle__c> vList = TopThreeListController.getTopThree();
        Test.stopTest();
        
        
        // ------------- Verify ------------- //
        System.assertEquals(3, vList.size());
    }


}