force-app/main/default/objects/Rental_Contract__c/Rental_Contract__c.object-meta.xml
<CustomObject>
    <description>Car rental contract formed by a rental company and one of its customers.</description>
    <label>Rental Contract</label>
    <nameField>
        <displayFormat>RC-{YY}{0000}</displayFormat>
        <label>Rental Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the contract.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Stationed_Depot__c.field-meta.xml
<CustomField>
    <fullName>Stationed_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stationed Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checked In</fullName>
                <default>true</default>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Lost/Stolen</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/classes/P0/VehicleTriggerHandler.cls
/*
 * ContactTrigger
 * Author: Wayne He
 * Date Modified: 2021-09-01
 * Description: Helper class for handling vehicle triggers.
 */

public class VehicleTriggerHandler {

    /*
     * Checks if there are not active rental contracts on the vehicles which prevent them from being checked in.
     * In addition, check if there are any active rental contracts for vehicles being attempted to be manually checked out.
     * Throws an error in Salesforce if an attempt on changing a vehicle's status is being made while a rental contract is still active,
     * or if the vehicle is being manually checked out without an active rental contract.
     * @param vehicles - A list of Vehicles to be inserted/updated.
     */
    public static void checkContractStatus(List<Vehicle__c> vehicles) {
        //Check contracts that involve this vehicle, and check if the contract is closed.
        for (Vehicle__c vehicle : vehicles) {
            List<Rental_Contract__c> contracts = [SELECT Id, Name, Status__c FROM Rental_Contract__c WHERE Vehicle__c = :vehicle.Id];

            //Check if there is an active contract for vehicles that are checked out'.
            //Skip vehicle if there is one, otherwise throw an error.
            if (vehicle.Status__c.equals('Checked Out')) {
                boolean hasActiveContract = false;
                for (Rental_Contract__c rentalContract : contracts) {
                    if (!rentalContract.Status__c.equals('Closed')) {
                        hasActiveContract = true;
                        break;
                    }
                }

                if (hasActiveContract)
                    continue;
                
                vehicle.Status__c.addError('Cannot manually check out vehicles. Please form a rental contract.');
            }
            else {
                for (Rental_Contract__c rentalContract : contracts) {
                    if (!rentalContract.Status__c.equals('Closed'))
                        vehicle.Status__c.addError('Cannot change status of vehicle while contract is still active: ' + rentalContract.Name);
                }
            }
        }
    }
    
    /*
     * Checks if the vehicles are still being checked out, and prevent stationing them to depots if they still are.
     * @param vehicles - A list of Vehicles to be updated.
     */
    public static void checkVehicleStatus(List<Vehicle__c> vehicles) {
        //Checks if vehicles are already checked out.
        for (Vehicle__c vehicle: vehicles) {
            if (vehicle.Status__c.equals('Checked Out')) {
                //Prevent stationing a vehicle to a depot.
                if (vehicle.Stationed_Depot__c != null)
                    vehicle.Stationed_Depot__c.addError('Cannot station a checked out vehicle to a depot.');
            }
        }
    }
}