force-app/main/default/objects/Rental_Contract__c/Rental_Contract__c.object-meta.xml
<CustomObject>
    <description>Car rental contract formed by a rental company and one of its customers.</description>
    <label>Rental Contract</label>
    <nameField>
        <displayFormat>RC-{YY}{0000}</displayFormat>
        <label>Rental Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Contract__c/fields/Actual_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Return_Date__c</fullName>
    <description>The date when the customer returned the vehicle.</description>
    <label>Actual Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>The customer who is signing the contract.</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Return_Date__c</fullName>
    <description>The date when the customer is expected to return the vehicle.</description>
    <label>Expected Return Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The date when the rental contract is formed.</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the contract.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Stationed_Depot__c.field-meta.xml
<CustomField>
    <fullName>Stationed_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stationed Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checked In</fullName>
                <default>true</default>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Lost/Stolen</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/classes/P0/RentalContractTriggerHandler.cls
/*
 * RentalContractTriggerHandler
 * Author: Wayne He
 * Date Modified: 2021-09-01
 * Description: Helper class for handling rental contact triggers.
 */

public class RentalContractTriggerHandler {
    
    /*
     * Grabs a list of Rental Contracts to be inserted, and check for any overdue contracts for their associated customers.
     * This will not allow customers to create new contracts unless they have resolved their overdue contracts.
     * @param contracts - A list of Contacts to be inserted.
     * @return A boolean value that determines if there is an overdue contract.
     */
    public static boolean checkCustomersForOverdueVehicles(List<Rental_Contract__c> contracts) {
        boolean noOverdueVehicles = true;

        //Get customers from the list of contracts.
        Set<Id> customers = new Set<Id>();
        for (Rental_Contract__c rentalContract : contracts) {
            customers.add(rentalContract.Customer__c);
        }
        
        //Fetch overdue contracts.
        integer overdueContracts = [SELECT COUNT() FROM Rental_Contract__c WHERE Customer__c IN :customers AND Status__c = 'Overdue'];
        if (overdueContracts > 0) {
            contracts[0].addError('Customer has an overdue contract. Please resolve this before creating a new contract.');
            noOverdueVehicles = false;
        }
        
        return noOverdueVehicles;
    }

    /*
     * Before inserting new contracts, this method makes sure that:
     * - The vehicle associated with a new contract is not already checked out.
     * - The contract's issue date does not take place after the current date.
     * - The contract's expected return date does not take place before the issue date.
     * Otherwise, it will throw an error and prevent the insert.
     * @param contracts - A list of Rental Contracts to insert.
     */
    public static void checkOutVehicle(List<Rental_Contract__c> contracts) {
        Map<Id, Vehicle__c> vehicleMap = getVehicleMap(contracts);
        
        //Iterate through each contract.
        for (Rental_Contract__c rentalContract : contracts) {
            //Check if the contract's associated vehicle is checked in. Abort if it is not.
            if (vehicleMap.get(rentalContract.Vehicle__c).Status__c.equals('Checked Out'))
                rentalContract.Vehicle__c.addError('Vehicle is not available for checking out.');
            
            //Check if the contract's issue date is later than current date. Abort if it is.
            if (rentalContract.Issue_date__c.daysBetween(Date.today()) < 0)
                rentalContract.Issue_Date__c.addError('Cannot issue a contract that starts at a later date than today.');
            
            //Check if the contract's expected return date is earlier than or the same as the issue date. Abort if it is.
            if (rentalContract.Expected_Return_Date__c.daysBetween(rentalContract.Issue_Date__c) >= 0)
                rentalContract.Expected_Return_Date__c.addError('Cannot issue a contract with an expected return date earlier than or at the issue date.');
        }
    }
    
    /*
     * Grabs a list of contracts and checks if the actual return dates do not occur before the issue date.
     * Reject of one of them does.
     * @param contracts - A list of Rental Contracts to update.
     */
    public static void checkReturnDate(List<Rental_Contract__c> contracts) {
        //Check if the actual return date takes place before the issue date. Abort if this is true.
        for (Rental_Contract__c rentalContract : contracts) {
            //Skip null values.
            if (rentalContract.Actual_Return_Date__c == null)
                continue;
            
            if (rentalContract.Actual_Return_Date__c.daysBetween(rentalContract.Issue_Date__c) > 0)
                rentalContract.Actual_Return_Date__c.addError('Return date cannot occur before the issue date.');
        }
    }
    
    /*
     * Takes in a list of contracts and changes their associated vehicles' statuses depending if they are being checked out or checked in.
     * @param contracts - A list of Rental Contracts to modify.
     * @param isCheckingOut - A boolean that states whether to check out those vehicles or not.
     */
    public static void changeVehicleStatus(List<Rental_Contract__c> contracts, boolean isCheckingOut) {
        Map<Id, Vehicle__c> vehicleMap = getVehicleMap(contracts);
        
        //Set status of each vehicle.
        for (Vehicle__c vehicle : vehicleMap.values()) {
            if (isCheckingOut) {
                vehicle.Status__c = 'Checked Out';
                vehicle.Stationed_Depot__c = null;
            }
            else {
                vehicle.Status__c = 'Checked In';
            }
            
        }
        
        //Attempt to update entries.
        try {
            update vehicleMap.values();
        } catch (DMLException e) {
            contracts[0].addError(e);
        }
    }
    
    /*
     * Checks to see if the contracts' new expected return dates happen before the old return dates.
     * Throw an error and reject if one of them does.
     * @param oldContacts - A list of Rental Contracts with original data.
     * @param newContacts - A list of the same Rental Contracts with updated data.
     */
    public static void postponeCheck(List<Rental_Contract__c> oldContracts, List<Rental_Contract__c> newContracts) {
        //Compare expected return dates for the two lists. If the new deadline is earlier than the old one, abort the update.
        for (integer i = 0; i < oldContracts.size(); i++) {
            if (oldContracts[i].Expected_Return_Date__c.daysBetween(newContracts[i].Expected_Return_Date__c) < 0)
                newContracts[i].Expected_Return_Date__c.addError('Cannot set the expected return date earlier than the current deadline: ' + oldContracts[i].Expected_Return_Date__c);
        }
    }
    
    /*
     * Helper method that generates a map of Vehicles with their record IDs from a given list of contracts.
     * This will throw an error if two contracts reference the same vehicle, so we want different vehicles for each contract.
     * @param contracts - A list of Rental Contracts.
     * @return A map of Vehicle IDs and their associated instances.
     */
    private static Map<Id, Vehicle__c> getVehicleMap(List<Rental_Contract__c> contracts) {
        //Get vehicles from contract list. Abort if there are duplicates.
        Set<Id> vehicleIds = new Set<Id>();
        for (Rental_Contract__c rentalContract : contracts) {
            if (!vehicleIds.contains(rentalContract.Vehicle__c))
                vehicleIds.add(rentalContract.Vehicle__c);
            else
                rentalContract.Vehicle__c.addError('Can only form a single contract with a checked out vehicle once.');
        }
        List<Vehicle__c> vehicles = [SELECT Id, Status__c FROM Vehicle__c WHERE Id IN :vehicleIds];
        return new Map<Id, Vehicle__c>(vehicles);
    }
}