force-app/main/default/objects/Rental_Contract__c/Rental_Contract__c.object-meta.xml
<CustomObject>
    <description>Car rental contract formed by a rental company and one of its customers.</description>
    <label>Rental Contract</label>
    <nameField>
        <displayFormat>RC-{YY}{0000}</displayFormat>
        <label>Rental Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Contract__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/globalValueSets/Car_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa-Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston-Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Bugatti</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citroen</fullName>
    </customValue>
    <customValue>
        <fullName>Daewoo</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Geely</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Koenigsegg</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Lancia</fullName>
    </customValue>
    <description>List of available automobile brands.
Popular brands fetched from:
- https://www.carlogos.org/popular-car-brands/
- https://www.topspeed.com/cars/makes/</description>
    <masterLabel>Car Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TopThreeListController.cls
public class TopThreeListController {
    
    // Assume the query return a list that has more than 3 elements.
    // This method return the a List<Vehicle__c> that contains the top 3 cars.
    @AuraEnabled
    public static List<Vehicle__c> getTopThree() {
        
        List<Vehicle__c> topThree = new List<Vehicle__c>();
        
        List<Rental_Contract__c> contractList = [SELECT Id, Vehicle__r.Name 
                                                 FROM Rental_Contract__c 
                                                 ORDER BY Vehicle__r.Name];
        // System.debug(contractList[3].Vehicle__r.Name);
        
        // Assume the map has more than 3 elements.
        Map<String, Integer> numOfContracts = new Map<String, Integer>();
        for (Rental_Contract__c contract : contractList) {
            if (!numOfContracts.containsKey(contract.Vehicle__r.Name)) {
                numOfContracts.put(contract.Vehicle__r.Name, 1);
            } else {
                numOfContracts.put(contract.Vehicle__r.Name, 
                                   numOfContracts.get(contract.Vehicle__r.Name) + 1);
            }
        }
        
        // List to hold the top 3 most popular vehicles. 
        List<String> vehicleName = new List<String>();
        vehicleName.add('');
        vehicleName.add('');
        vehicleName.add('');
        List<Integer> num = new List<Integer>();
        num.add(0);
        num.add(0);
        num.add(0);

        // Get the name of the top 3 cars.
        Integer counter = 0;
        for (String key : numOfContracts.keySet()) {
            if (counter < 3) { // Set the top 3 to the first 3.
                if (vehicleName[counter] == '') {
                    vehicleName[counter] = key;
                    num[counter] = numOfContracts.get(key);
                    counter++;
                }
            } else {
                if (numOfContracts.get(key) > num[0]) { // The current vehicle has more contract than #1.
                    // Set #2 become #3.
                    vehicleName[2] = vehicleName[1];
                    num[2] = num[1];
                    // Set #1 become #2.
                    vehicleName[1] = vehicleName[0];
                    num[1] = num[0];
                    // Set current vehicle to #1.
                    vehicleName[0] = key;
                    num[0] = numOfContracts.get(key);    
                } else if (numOfContracts.get(key) > num[1]) { // The current vehicle has more contract than #2.
                    // Set #2 become #3.
                    vehicleName[2] = vehicleName[1];
                    num[2] = num[1];
                    // Set current vehicle to #2.
                    vehicleName[1] = key;
                    num[1] = numOfContracts.get(key);  
                } else if (numOfContracts.get(key) > num[2]) { // The current vehicle has more contract than #3.
                    // Set current vehicle to #3.
                    vehicleName[2] = key;
                    num[2] = numOfContracts.get(key); 
                }
            }
        }
        // System.debug(vehicleName);
        // System.debug(num);
        
        // Query fot the top 3 cars and save them in a list.
        List<Vehicle__c> top1 = [SELECT Id, Name, Vehicle_Make__c 
                                 FROM Vehicle__C 
                                 WHERE Name = :vehicleName[0] 
                                 LIMIT 1];
        List<Vehicle__c> top2 = [SELECT Id, Name, Vehicle_Make__c 
                                 FROM Vehicle__C 
                                 WHERE Name = :vehicleName[1] 
                                 LIMIT 1];
        List<Vehicle__c> top3 = [SELECT Id, Name, Vehicle_Make__c 
                                 FROM Vehicle__C 
                                 WHERE Name = :vehicleName[2] 
                                 LIMIT 1];
        topThree.add(top1[0]);
        topThree.add(top2[0]);
        topThree.add(top3[0]);
        System.debug(topThree);

        return topThree;
        
    }
    
}