force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Discount_Code__c</fullName>
    <description>Discount code for reduced rental rates</description>
    <label>Discount Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/dealsAndPromosControllerTest.cls
@isTest
private class dealsAndPromosControllerTest {
    @TestSetup
    static void makeData(){
        Discount__c disc = new Discount__c();
        disc.Name = 'test';
        disc.Discount_Code__c = 'test';
        insert disc;
    }
    
    @isTest
    static void getPublicDiscounts() {
        List<Discount__c> discList = [SELECT Id, Name FROM Discount__c];
        dealsAndPromosController.getPublicDiscounts();
        System.assertEquals(1, discList.size());
    }

    @isTest
    static void findDiscount() {
        List<Discount__c> dList = [SELECT Id, Name FROM Discount__c];
        Discount__c testdisc = dealsAndPromosController.findDiscount('test');
        System.assertEquals(1, dList.size());
        System.assertEquals('test', testdisc.Discount_Code__c);
    }
}