force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Discount_Code__c</fullName>
    <description>Discount code for reduced rental rates</description>
    <label>Discount Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <description>Percent discounted from rental rate</description>
    <label>Discount Percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this discount publicly available?</description>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/dealsAndPromosController.cls
public class dealsAndPromosController {
    @AuraEnabled
    public static List<Discount__c> getPublicDiscounts(){
        List<Discount__c> publicDiscounts = [SELECT Id, Name, Discount_Percent__c, Discount_Code__c, Public__c 
                                             FROM Discount__c
                                             WHERE Public__c = true];
        return publicDiscounts;
    }
    
    @AuraEnabled
    public static List<Discount__c> getAllDiscounts() {
        List<Discount__c> allDiscounts = [SELECT Id, Name, Discount_Percent__c, Discount_Code__c, Public__c FROM Discount__c];
        return allDiscounts;
    }
}