force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Depot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Base_Rental_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rental_Rate__c</fullName>
    <label>Base Rental Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Stationed_Depot__c.field-meta.xml
<CustomField>
    <fullName>Stationed_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stationed Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checked In</fullName>
                <default>true</default>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Lost/Stolen</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Identification_Number__c</fullName>
    <description>The unique number assigned to this vehicle.</description>
    <externalId>true</externalId>
    <label>Vehicle Identification Number</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <label>Vehicle Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/globalValueSets/Car_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa-Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston-Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Bugatti</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citroen</fullName>
    </customValue>
    <customValue>
        <fullName>Daewoo</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Geely</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Koenigsegg</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Lancia</fullName>
    </customValue>
    <customValue>
        <fullName>Toyota</fullName>
    </customValue>
    <description>List of available automobile brands.
Popular brands fetched from:
- https://www.carlogos.org/popular-car-brands/
- https://www.topspeed.com/cars/makes/</description>
    <masterLabel>Car Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/P0/VehicleTriggerTest.cls
/*
 * ContactTrigger
 * Author: Wayne He
 * Date Modified: 2021-09-01
 * Description: Unit test class for the vehicle trigger.
 */

 @isTest
private class VehicleTriggerTest {
    
    @TestSetup
    static void makeData(){
        TestData.createTestData();
    }

    @isTest static void addVehicleTest() {
        Vehicle__c newVehicle = new Vehicle__c(Name = 'Toyota Camry 2020 Black', Vehicle_Identification_Number__c = 'FAKE1252211234211255', Base_Rental_Rate__c = 42.61, Vehicle_Year__c = 2020, Vehicle_Make__c = 'Toyota', Vehicle_Model__c = 'Camry');
        insert newVehicle;
    }

    @isTest static void manualCheckInTest() {

        try {
            List<Vehicle__c> vehicles = [SELECT Status__c FROM Vehicle__c WHERE Status__c = 'Checked Out'];
            vehicles[0].Status__c = 'Checked In';
            update vehicles[0];

            System.assert(false, 'Was able to somehow change the vehicle status while it was checked out. Perhaps there was no active rental contract associated with it?');
        }
        catch (DMLException e) {
            System.assert(e.getMessage().contains('Cannot change status of vehicle while contract is still active: '));
        }
    }

    @isTest static void manualCheckOutTest() {
        try {
            List<Vehicle__c> vehicles = [SELECT Status__c FROM Vehicle__c WHERE Status__c != 'Checked Out'];
            vehicles[0].Status__c = 'Checked Out';
            update vehicles[0];

            System.assert(false, 'Was able to somehow manually check out a vehicle without forming a contract...');
        }
        catch (DMLException e) {
            System.assert(e.getMessage().contains('Cannot manually check out vehicles. Please form a rental contract.'));
        }
    }

    @isTest static void manualStationTest() {
        try {
            List<Vehicle__c> vehicles = [SELECT Status__c FROM Vehicle__c WHERE Status__c = 'Checked Out'];
            Depot__c depot = [SELECT Id FROM Depot__c LIMIT 1];
            vehicles[0].Stationed_Depot__c = depot.Id;
            update vehicles[0];

            System.assert(false, 'Was able to station a checked out vehicle to a depot.');
        }
        catch (DMLException e) {
            System.assert(e.getMessage().contains('Cannot station a checked out vehicle to a depot.'));
        }
    }
}