force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Depot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>The address where the depot is located.</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depot__c/fields/Depot_Manager__c.field-meta.xml
<CustomField>
    <fullName>Depot_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The employee who runs the depot.</description>
    <label>Depot Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Depots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depot__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <description>The company who owns this depot.</description>
    <label>Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Depots</relationshipLabel>
    <relationshipName>Depots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VF Controllers/DepotController.cls
public class DepotController {

    static final Integer MAX_ENTRIES_PER_PAGE = 10;
    
    public List<Account> accounts {get; private set;}
    public List<Depot__c> depots {get; private set;}
    
    public String accountId {get; set;}
    public String pageNumber {get; set;}

    public String nameFilter {get; set;}
    public String locationFilter {get; set;}
    
    public DepotController() {
        accounts = [SELECT Id, Name FROM Account];
        filterDepots();
    }
    
    public List<SelectOption> getAccountItems() {
        List<SelectOption> items = new List<SelectOption>();
        for (Account acc : accounts) {
            items.add(new SelectOption(acc.Id, acc.Name));
        }
        accountId = items[0].getValue();
        return items;
    }
    
    public Integer getFirstIndex() {
        return (Integer.valueOf(pageNumber) - 1) * MAX_ENTRIES_PER_PAGE;
    }
    
    public Integer getNumEntriesPerPage() {
        return MAX_ENTRIES_PER_PAGE;
    }
    
    public List<SelectOption> getPageNumbers() {
        List<SelectOption> pages = new List<SelectOption>();
        Integer totalPages = (Integer) Math.ceil((Decimal) depots.size() / MAX_ENTRIES_PER_PAGE);
        Integer i = 1;
        do {
            pages.add(new SelectOption(String.valueOf(i), String.valueOf(i)));
            i++;
        } while (i <= totalPages);
        return pages;
    }
    
    public void filterDepots() {
        String soqlNameFilter = '%' + nameFilter + '%';
        String soqlLocationFilter = '%' + locationFilter + '%';

        depots = [SELECT Id, Name, Owner__r.Name, Depot_Manager__c, Address__c, Primary_Phone__c FROM Depot__c
            WHERE Owner__c = :accountId AND Name LIKE :soqlNameFilter AND Address__c LIKE :soqlLocationFilter ORDER BY Name];

        //Reset page number and filter details after refreshing depot list with new data.
        pageNumber = '1';
    }

    public void resetFilters() {
        nameFilter = '';
        locationFilter = '';
        filterDepots();
    }

    public PageReference selectDepot() {
        PageReference pf = new PageReference('/apex/LandingPage');
        pf.getParameters().put('depot_id', System.currentPageReference().getParameters().get('depot_id'));
        return pf;
    }
}