force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Depot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <description>The company who owns this depot.</description>
    <label>Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Depots</relationshipLabel>
    <relationshipName>Depots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/Rental_Contract__c.object-meta.xml
<CustomObject>
    <description>Car rental contract formed by a rental company and one of its customers.</description>
    <label>Rental Contract</label>
    <nameField>
        <displayFormat>RC-{YY}{0000}</displayFormat>
        <label>Rental Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Contract__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>The company that is offering a contract.</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>The customer who is signing the contract.</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Return_Date__c</fullName>
    <description>The date when the customer is expected to return the vehicle.</description>
    <label>Expected Return Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The date when the rental contract is formed.</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Issuing_Depot__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The depot that is renting out the vehicle.</description>
    <label>Issuing Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Rental Contracts (Issuing Depot)</relationshipLabel>
    <relationshipName>Rental_Contracts_Issue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the contract.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Stationed_Depot__c.field-meta.xml
<CustomField>
    <fullName>Stationed_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stationed Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checked In</fullName>
                <default>true</default>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Lost/Stolen</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionController.cls
public class TransactionController {
    public Date issueDate{get;set;}
    public Date expectedReturnDate{get;set;}
    public decimal tp{get;set;}
    public String selectedId{get;set;}
    public Date birthdayDate{get;set;}
    public String email{get;set;}
    public String firstName{get;set;}
    public String lastName{get;set;}
    List<selectOption> vehicleOptions = new List<selectOption>();
    public List<selectOption> getCarNames() {
        for(Vehicle__c vn : [SELECT Name FROM Vehicle__c WHERE Status__c != 'Lost/Stolen' OR Status__c != 'Decomissioned']) {
            vehicleOptions.add(new selectOption(vn.Id, vn.Name));
        }
        return vehicleOptions;
    }
    public void totalPrice(){
        if(issueDate == null || expectedReturnDate == null){
            return;
        }
        else{
        tp = issueDate.daysBetween(expectedReturnDate) * 25.77;
        }
    }
    public PageReference saveRecord() {
        Rental_Contract__c newRental = new Rental_Contract__c();
        List<Contact> existingContacts = [SELECT id, email FROM Contact WHERE Email = :email];
        if(existingContacts.size() == 0) {
            Contact customer = new Contact(FirstName = firstName, LastName= lastName, Birthdate = birthdayDate, Email = email);
            insert customer;
            newRental.Customer__c = customer.Id;
        } else {
            newRental.Customer__c = existingContacts[0].id;
        }
        newRental.Issue_Date__c = issueDate;
        newRental.Expected_Return_Date__c = expectedReturnDate; 
        newRental.Status__c = 'Active';
        newRental.Vehicle__c = selectedId;
        List<Vehicle__c> vehicleDepot = [SELECT id, stationed_Depot__c FROM Vehicle__c WHERE id =: selectedId]; 
        newRental.Issuing_Depot__c = vehicleDepot[0].stationed_Depot__c;
        List<Depot__c> depotList = [SELECT id, Owner__c FROM Depot__c WHERE id =: vehicleDepot[0].stationed_Depot__c];
        newRental.Company__c = depotList[0].Owner__c;
        insert newRental;
        PageReference pageRef = new PageReference('/apex/thankYou');
        pageRef.getParameters().put('depot_id',System.currentPageReference().getParameters().get('depot_id'));
        return pageRef;
    }
}