force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Depot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <description>The company who owns this depot.</description>
    <label>Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Depots</relationshipLabel>
    <relationshipName>Depots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Transaction__c/Purchase_Transaction__c.object-meta.xml
<CustomObject>
    <label>Purchase Transaction</label>
    <nameField>
        <label>Purchase Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Transaction__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The depot where the vehicles will be deployed to.</description>
    <label>Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Purchase Transactions</relationshipLabel>
    <relationshipName>Purchase_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Base_Rental_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rental_Rate__c</fullName>
    <label>Base Rental Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Purchase_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Transaction</label>
    <referenceTo>Purchase_Transaction__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Identification_Number__c</fullName>
    <description>The unique number assigned to this vehicle.</description>
    <externalId>true</externalId>
    <label>Vehicle Identification Number</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <label>Vehicle Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Car_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa-Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston-Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Bugatti</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citroen</fullName>
    </customValue>
    <customValue>
        <fullName>Daewoo</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Geely</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Koenigsegg</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Lancia</fullName>
    </customValue>
    <description>List of available automobile brands.
Popular brands fetched from:
- https://www.carlogos.org/popular-car-brands/
- https://www.topspeed.com/cars/makes/</description>
    <masterLabel>Car Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CarSalesControllerTest.cls
@isTest
private class CarSalesControllerTest {
    @TestSetup
    static void makeData(){
        Vehicle__c vec = new Vehicle__c();
        vec.Name = 'testname';
        vec.Vehicle_Make__c = 'Acura';
        vec.Vehicle_Model__c = 'testmodel';
        vec.Vehicle_Identification_Number__c = '123456789';
        vec.Base_Rental_Rate__c = 100;
        vec.Vehicle_Year__c = 2020;
        
        Purchase_Transaction__c pur = new Purchase_Transaction__c();
        pur.Name = 'purtestname';
        
        Account acc = new Account();
        acc.Name = 'testacc';
        insert acc;
        Depot__c dep = new Depot__c();
        dep.Name = 'testdep';
        dep.Owner__c = acc.Id;
        insert vec;
        insert pur;
        insert dep;
        //CarSalesController testcont = new CarSalesController();
    }
    
    
    @isTest
    static void savecar() {
        Purchase_Transaction__c pur = [SELECT Id FROM Purchase_Transaction__c WHERE Name = 'purtestname'];
        Vehicle__c vehic = [SELECT Id, Purchase_Transaction__c FROM Vehicle__c WHERE Name = 'testname'];
        CarSalesController.saveCar(vehic, pur);
        System.assertEquals(pur.Id, vehic.Purchase_Transaction__c);
    }

    @isTest
    static void getCompanies() {
        List<Account> accList = [SELECT Id, Name FROM Account];
        CarSalesController.getCompanies();
        System.assertEquals(1, accList.size());
    }  
    
    @isTest
    static void getDepots() {
        List<Depot__c> depList = [SELECT Id, Name FROM Depot__c];
        CarSalesController.getDepots();
        System.assertEquals(1, depList.size());
    }
}