force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Depot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>The address where the depot is located.</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depot__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <description>The company who owns this depot.</description>
    <label>Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Depots</relationshipLabel>
    <relationshipName>Depots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/Rental_Contract__c.object-meta.xml
<CustomObject>
    <description>Car rental contract formed by a rental company and one of its customers.</description>
    <label>Rental Contract</label>
    <nameField>
        <displayFormat>RC-{YY}{0000}</displayFormat>
        <label>Rental Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Contract__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>The company that is offering a contract.</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>The customer who is signing the contract.</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Return_Date__c</fullName>
    <description>The date when the customer is expected to return the vehicle.</description>
    <label>Expected Return Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Issuing_Depot__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The depot that is renting out the vehicle.</description>
    <label>Issuing Depot</label>
    <referenceTo>Depot__c</referenceTo>
    <relationshipLabel>Rental Contracts (Issuing Depot)</relationshipLabel>
    <relationshipName>Rental_Contracts_Issue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the contract.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rental_Contract__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Rental Contracts</relationshipLabel>
    <relationshipName>Rental_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Base_Rental_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rental_Rate__c</fullName>
    <label>Base Rental Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checked In</fullName>
                <default>true</default>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Lost/Stolen</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Identification_Number__c</fullName>
    <description>The unique number assigned to this vehicle.</description>
    <externalId>true</externalId>
    <label>Vehicle Identification Number</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <label>Vehicle Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Car_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa-Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston-Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Bugatti</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Citroen</fullName>
    </customValue>
    <customValue>
        <fullName>Daewoo</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Geely</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hudson</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Koenigsegg</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Lancia</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Toyota</fullName>
    </customValue>
    <description>List of available automobile brands.
Popular brands fetched from:
- https://www.carlogos.org/popular-car-brands/
- https://www.topspeed.com/cars/makes/</description>
    <masterLabel>Car Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/P0/TestData.cls
/*
 * ContactTrigger
 * Author: Wayne He
 * Date Modified: 2021-09-01
 * Description: Contains initial test data shared by all test classes.
 */

 @isTest
public class TestData {
    
    //Made private and added @TestVisible annotation so only test methods can access it.
    @TestVisible
    private static void createTestData() {
        List<sObject> initialDB = new List<sObject>();
        List<sObject> depotDB = new List<sObject>();

        //Account
        initialDB.add(new Account(Name = 'Test Company'));

        //Contacts
        initialDB.add(new Contact(FirstName = 'Ben', LastName = 'Steward', Birthdate = Date.newInstance(1980, 2, 16), Email = 'some@email.com'));
        initialDB.add(new Contact(FirstName = 'John', LastName = 'Warner', Birthdate = Date.newInstance(1967, 6, 2), Email = 'the@email.com'));
        initialDB.add(new Contact(FirstName = 'Bob', LastName = 'Builder', Birthdate = Date.newInstance(1977, 10, 24), Email = 'bob@email.com'));
        initialDB.add(new Contact(FirstName = 'Billy', LastName = 'Bob', Birthdate = Date.newInstance(1998, 3, 14), Email = 'billy@email.com'));
        initialDB.add(new Contact(FirstName = 'Jane', LastName = 'Steward', Birthdate = Date.newInstance(1982, 4, 30), Email = 'some1@email.com'));

        //Vehicles
        initialDB.add(new Vehicle__c(Name = 'Toyota Camry 2019 Black', Vehicle_Identification_Number__c = 'FAKE1252211242211255', Base_Rental_Rate__c = 40.28, Vehicle_Year__c = 2019, Vehicle_Make__c = 'Toyota', Vehicle_Model__c = 'Camry'));
        initialDB.add(new Vehicle__c(Name = 'Honda CRV 2019 Silver', Vehicle_Identification_Number__c = 'FAKE1252218653263121', Base_Rental_Rate__c = 43.28, Vehicle_Year__c = 2019, Vehicle_Make__c = 'Honda', Vehicle_Model__c = 'CRV'));
        initialDB.add(new Vehicle__c(Name = 'Lexus ES350 2022 Red', Vehicle_Identification_Number__c = 'FAKE1252283324562268', Base_Rental_Rate__c = 67.39, Vehicle_Year__c = 2022, Vehicle_Make__c = 'Lexus', Vehicle_Model__c = 'ES350'));
        initialDB.add(new Vehicle__c(Name = 'Toyota Camry 2019 Black', Vehicle_Identification_Number__c = 'FAKE1252285323767642', Base_Rental_Rate__c = 40.28, Vehicle_Year__c = 2019, Vehicle_Make__c = 'Toyota', Vehicle_Model__c = 'Camry'));

        //Insert initalDB and grab account first since depots require Account id.
        //Will need lists of contacts and vehicles first for rental contracts later.
        insert initialDB;
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Company'];
        List<Contact> customers = [SELECT Id FROM Contact];
        List<Vehicle__c> vehicles = [SELECT Id, Status__c FROM Vehicle__c];

        //Depots
        depotDB.add(new Depot__c(Name = 'Test Company Orlando', Owner__c = acc.Id, Address__c = '123 Sesame Street, Orlando FL 32715'));
        depotDB.add(new Depot__c(Name = 'Test Company Ontario', Owner__c = acc.Id, Address__c = '456 Fake Street, Ontario CA 94316'));

        //Insert data and grab depot data since it is required for rental contracts.
        insert depotDB;
        List<Depot__c> depots = [SELECT Id FROM Depot__c];

        //Rental Contract
        Rental_Contract__c testContract = new Rental_Contract__c(Company__c = acc.Id, Customer__c = customers[0].Id, Vehicle__c = vehicles[0].Id, Issuing_Depot__c = depots[0].Id, Expected_Return_Date__c = Date.today().addDays(7));

        insert testContract;
    }
}