force-app/main/default/objects/Depot__c/Depot__c.object-meta.xml
<CustomObject>
    <label>Depot</label>
    <nameField>
        <label>Depot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>The address where the depot is located.</description>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depot__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <description>The company who owns this depot.</description>
    <label>Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Depots</relationshipLabel>
    <relationshipName>Depots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NavListController.cls
public without sharing class NavListController {
	@AuraEnabled
   public static List<Account> getAccounts() {
       return [SELECT Id, Name, Industry, Phone
       FROM Account ORDER BY LastModifiedDate];
   }
    
    @AuraEnabled
    public static list<Depot__c> getRelatedList(Id recordId)
    {
        List<Depot__c> depList = [Select id, name, address__c from Depot__c where Owner__c=:recordId ];
        return depList;
    }
}